### ISSUE TITLE
Brew Tap not working

### ISSUE THREAD

**Issue by lquessenberry** [prologic/httpfs#4]
The brew tap is asking me for my user and pass to GitHub and then it can't find the repo.

**Comment by prologic** [comment]
I will investigate this tonight after work. Thanks for reporting!

Any further information you find in the meantime would be highly valuable!

cheers
james


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
Fixed
