### ISSUE TITLE
Input/output error when trying to access mountpoint

### ISSUE THREAD

**Issue by probonopd** [prologic/httpfs#6]
Getting an Input/output error when trying to mount a file over https. Note I don't have a directory, just a file that I need to mount.

```
linux@linux:~/httpfs> sudo /home/linux/go/bin/httpfsmount -url https://github.com/AppImage/AppImageUpdate/releases/download/continuous/AppImageUpdate-x86_64.AppImage -mount /mnt

linux@linux:~/httpfs> ls /mnt/
ls: reading directory '/mnt/': Input/output error
```

**Comment by probonopd** [comment]
Also getting the error when trying to mount a directory:

```
linux@linux:~/httpfs> sudo /home/linux/go/bin/httpfsmount -url http://download.opensuse.org/repositories/home:/jsevans/AppImage/ -mount /mnt

linux@linux:~/httpfs> ls /mnt/
ls: reading directory '/mnt/': Input/output error
```

**Comment by probonopd** [comment]
There is also httpfs2 which supposedly supports TLS but seemingly still does not like https URLs:

```
linux@linux:~/httpfs2-0.1.5> ./httpfs2 -f "https://github.com/AppImage/AppImageUpdate/releases/download/continuous/AppImageUpdate-x86_64.AppImage" /mnt
Invalid protocol in url: https://github.com/AppImage/AppImageUpdate/releases/download/continuous/AppImageUpdate-x86_64.AppImage
invalid url: https://github.com/AppImage/AppImageUpdate/releases/download/continuous/AppImageUpdate-x86_64.AppImage
```

**Comment by prologic** [comment]
Hmmm this wsn't really designed to mount arbitrary http endpoints :/

**Comment by probonopd** [comment]
Which ones was it designed for @prologic?

**Comment by prologic** [comment]
It has its own backend `httpfsd` that you run separately against a file system you want to expose over HTTP. Then you use `httpfsmount` to "mount it" via FUSE.

There have been small efforts to support the Apache-style directory listing and static file serving.

It **is** possible to extend this feature set in limited ways to support "mounting" arbitrary URI(s) with known good formats; but it wasn't designed for this.

**Comment by probonopd** [comment]
I would be very interested in mounting AppImage files (squashfs files) over http(s).

**Comment by prologic** [comment]
What's your use-case? Do you have bandwidth to collaborate on this?

**Comment by probonopd** [comment]
> What's your use-case? 

An [AppImage](https://appimage.org/) is a squashfs file that contains an application, libraries, icons, documentation, and other files. I am building AppImageHub, a crowd-sourced central directory of AppImages. There is a (lightweight) quality checking for AppImages using Travis CI, as part of which we are downloading every AppImage that is being processed. If we could just mount it over the network instead, this process would be faster and more lightweight since only the portions that are actually needed would have to be downloaded, instead of the whole thing.

> Do you have bandwidth to collaborate on this?

Since I am doing this in my spare time, my bandwith is more or less limited to _testing_ but possibly @TheAssassin could collaborate on code level?

**Comment by TheAssassin** [comment]
@probonopd what you were probably looking for is WebDAV (server support needed as well), and some FUSE implementation for mounting it (there's plenty, e.g., gvfs, davfs2, ...). (*Disclaimer: Yes, I know that WebDAV sucks. I use it occassionally with SabreDAV and Nextcloud servers. I haven't tried httfs yet.*)

What @probonopd wants to do is mount a file without having to download it, and then do all things you could do with a normal file, like executing, reading (random access), etc.

I don't know how I could help here, @probonopd. First of all, there'd need to be support for mounting files as-is without requiring a daemon serving the files in either WebDAV or httpfs or whatever solution you're using. This seems possible but highly inefficient. HTTP wasn't made for streaming files, you can't read on an HTTP request like you could on a file. There's also other limitations. (That's why they invented WebDAV at all. I even believe to remember most WebDAV implementations cache files on the local disk as well, you just don't notice as this happens transparently.).

Knowing how AppImages work: @probonopd for what you are trying to do a download seems to be the best way of dealing with AppImages.

**Comment by probonopd** [comment]
> what you were probably looking for is WebDAV

No, since the AppImages are hosted by people (not: by me) on normal https servers mostly (e.g., on GitHub Releases).

> Knowing how AppImages work: @probonopd for what you are trying to do a download seems to be the best way of dealing with AppImages.

...unless the AppImage to be checked happens to be for a, say, game that bundles 10 GB worth of _game data_...

**Comment by TheAssassin** [comment]
> Knowing how AppImages work: @probonopd for what you are trying to do a download seems to be the best way of dealing with AppImages.
>>  ...unless the AppImage to be checked happens to be for a, say, game that bundles 10 GB worth of game data...

That doesn't make HTTP a suitable protocol, though. Also, as @prologic pointed out, httpfs seems to _require_ a custom backend as well.

**Comment by prologic** [comment]
> That doesn't make HTTP a suitable protocol, though. Also, as @prologic pointed out, httpfs seems to require a custom backend as well to be able to work with files properly.

I'm open to other ideas. httpfs was mostly en experimental (*that works but has some performance issues*).

@TheAssassin You are correct; HTTP is the worst protocol here. HTTP/2 would be better; but GRPC / Protobuf / Thrift or even nanomsg could be better suited here.

The httpfsd backend actually *tries* to implement (*as efficiently as it can*) an appropriate API to fulfill FUSE requests over HTTP; i.e: the `httpfsmount` client only knows how to really talk to a `httpfsd` backend (*right now*)

**Comment by TheAssassin** [comment]
@prologic it doesn't matter whether it's HTTP or HTTP/2, both are not really suited for "randomly accessing" files like a local file (except for HTTP/2 being a bit more efficient than HTTP with `Connection: keepalive`...). While possible with a ton of range requests, I doubt it'd be a good idea to try to "execute" a file over HTTP. Same goes for any FUSE driver, e.g., SSHFS and others, without caching. And if you have to cache large parts of the file, I don't see a big advantage to downloading the file in advance...

It's more of a question of the cost-benefit ratio. I think it's too low. So, while technically possible (we could call it an experiment as well), I guess the result is the FUSE backend having to download most of the file while being `fread()` to execute it or something like that...

**Comment by prologic** [comment]
@TheAssassin You're forgetting the most important part; the `httpfsd` backend **does** the `fread()` at the requested block positions from the client `httpfsmount`; so in a manner of speaking httpfs does not ever download the entire file at all. I haven't done any in-depth performance profiling but the performance hit may be lack of cache and just the overhead of the req/res on every I/O.

**Comment by TheAssassin** [comment]
@prologic okay, might be. On the other hand, there's @probonopd who's requesting that this stuff works with any random HTTP server (e.g., Apache's httpd, nginx, ...). And, as you say, only with httpfsd a somewhat acceptable performance can be achieved.

Also, we should not forget that average web servers' maintainers are most likely not interested in providing a "mountable" HTTP endpoint. Nowadays, with CDNs, and tons of redirections to unpredictable infrastructure (e.g., GitHub Releases -> AWS endpoint (with a ton of parameters)), you'd have to request the original URL all the time and follow the redirection multiple times, potentially requiring you to connect to different servers, adding overhead like establishing a connection to multiple hosts (including the expensive TLS handshake etc.), that HTTP/2 (or HTTP1 with keepalive) try to eliminate. Single-host setups with httpfsd can be optimized for these use cases, even "normal" HTTP/2 servers without complicated CDN setups might work fine.

I have doubts @probonopd's use case to mount files from `<insert random host/service here>` would work well therefore. I'm not saying that it isn't possible to issue a ton of range requests in a FUSE backend. I'd really like to see a performance comparison of "httpfsd" vs. "average HTTP server".

**Comment by probonopd** [comment]
Performance is not really critical in my use case, but efficiency is. As for the redirections, we can resolve them prior to having httpfs mount the file.

I had done this using `httpfs2` a while ago at https://gist.github.com/probonopd/ff332e12ffaaf3fbb18ea2d853ff3843 and "basically" had it working, so I think it _is_ doable...

**Comment by TheAssassin** [comment]
> As for the redirections, we can resolve them prior to having httpfs mount the file.

Please re-read my last comment why you can _not_ just resolve them.

**Comment by prologic** [comment]
@TheAssassin Yes :) The httpfs client `httpfsmount` **can never** work and be **performant** (*at all*) with any arbitrary HTTP server :)
